description: >
  An archive of works about anarchy, philosophy, physics, transhumanism, and
  more.
lang: en_US
logo: /assets/img/aw.png
plugins:
  - jekyll-seo-tag
  - jekyll-feed
repository: trewbot/anarchy.website
social:
  name: Una J. Ada
  links:
    - https://github.com/trewbot
    - https://twitter.com/trewbot
    - https://www.youtube.com/channel/UC4HsBGB0z0g77wVdrCssgIQ
theme: jekyll-theme-minimal
title: anarchy.website
twitter:
  username: trewbot
url: https://anarchy.website
