description: >
  An archive of works about anarchy, philosophy, physics, transhumanism, and
  more.
kramdown:
  syntax_highlighter_opts:
    disable: true
  footnote_backlink: '&#x21A9;&#xFE0E;'
lang: en_US
logo: /assets/img/me.jpg
markdown: kramdown
plugins:
  - jekyll-seo-tag
repository: trewbot/anarchy.website
social:
  name: Una J. Ada
  links:
    - https://github.com/trewbot
    - https://twitter.com/trewbot
    - https://www.youtube.com/channel/UC4HsBGB0z0g77wVdrCssgIQ
theme: jekyll-theme-minimal
title: anarchy.website
twitter:
  username: trewbot
url: https://anarchy.website
